"""lane — run several pieces of work side by side, each in its own git worktree."""

try:
    # Generated by hatch-vcs from the git tag; see pyproject.toml. Present in a
    # synced checkout, in a wheel, and inside the binary.
    from lane._version import __version__
except ImportError:  # pragma: no cover — an unbuilt, unsynced source tree
    # Deliberately not a plausible-looking number: a wrong version that reads
    # like a real one is worse than one that announces itself as unknown.
    __version__ = "0+unknown"

# The version arrives by an import, so `--strict` needs telling it is deliberate.
__all__ = ["__version__"]
