"""The entry point: exactly two flags, then hand off to the interactive session.

lane takes no subcommands. That is deliberate and documented in AGENTS.md — the
menu is the only way in, so there is only ever one thing to keep in step with
what the app can do.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from typing import NoReturn

from lane import buildinfo
from lane.environment import Environment, RealEnvironment

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_NO_TTY = 3


class _UsageError(Exception):
    """argparse wanted to exit. We print our own prose instead."""


# Written by hand rather than generated by argparse: there are two flags, and the
# useful half of this text is the paragraph explaining that there is nothing else
# to type. Deliberately never lists an action — the menu does that, at runtime,
# from one table.
HELP = f"""\
{buildinfo.APP} — run several pieces of work side by side, each in its own git worktree

usage: {buildinfo.APP} [--version | --help]

  -V, --version   print the version and build fingerprint
  -h, --help      print this message

{buildinfo.APP} is interactive and takes no subcommands. Run it with no arguments to
start a session: it shows a menu of everything it can do, walks you through the
action you pick, and returns you to the menu afterwards. Choose quit to leave.

A terminal is required. These two flags are the exception and work anywhere.\
"""


class _Parser(argparse.ArgumentParser):
    def error(self, message: str) -> NoReturn:
        raise _UsageError(message)

    def exit(self, status: int = 0, message: str | None = None) -> NoReturn:  # noqa: ARG002
        raise _UsageError(message or "")


def _parser() -> argparse.ArgumentParser:
    parser = _Parser(prog=buildinfo.APP, add_help=False)
    parser.add_argument("-V", "--version", action="store_true")
    parser.add_argument("-h", "--help", action="store_true")
    return parser


def _refuse(offenders: Sequence[str]) -> int:
    named = ", ".join(offenders)
    print(f"{buildinfo.APP}: does not understand {named}", file=sys.stderr)
    print(
        f"{buildinfo.APP} takes no subcommands — it is interactive. "
        f"Run '{buildinfo.APP}' with no arguments.",
        file=sys.stderr,
    )
    print(
        f"The only arguments are --version and --help. See '{buildinfo.APP} --help'.",
        file=sys.stderr,
    )
    return EXIT_USAGE


def main(argv: list[str] | None = None, *, environment: Environment | None = None) -> int:
    try:
        args, extras = _parser().parse_known_args(argv)
    except _UsageError:
        # Anything argparse could not parse is, for lane, an unknown argument.
        return _refuse(list(argv if argv is not None else sys.argv[1:]))

    if extras:
        return _refuse(extras)

    # Both flags are answered before any prerequisite is consulted, so they work
    # in CI and on a machine where nothing lane needs is installed.
    if args.version:
        print(buildinfo.version_line())
        return EXIT_OK

    if args.help:
        print(HELP)
        return EXIT_OK

    env = environment if environment is not None else RealEnvironment()

    # A TTY is required, and there is no half-working non-interactive fallback to
    # maintain. This is checked after the two flags and before anything else.
    if not env.is_interactive():
        print(
            f"{buildinfo.APP} is interactive and needs a terminal, "
            "but its input or output is not one.",
            file=sys.stderr,
        )
        print(
            f"Run '{buildinfo.APP}' directly in a terminal. "
            f"Only --version and --help work elsewhere.",
            file=sys.stderr,
        )
        return EXIT_NO_TTY

    # Imported here so that --version and --help never pay for the UI stack, and
    # so they keep working on a machine where nothing lane needs is installed.
    from lane import app

    return app.run(env)
